//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _17DemoEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Trainers = new HashSet<Trainer>();
        }
    
        public int TopicID { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<Trainer> Trainers { get; set; }
    }
}
