//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18DemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp
    {
        public Emp()
        {
            this.EmpDetails = new HashSet<EmpDetail>();
        }
    
        public int No { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<EmpDetail> EmpDetails { get; set; }
    }
}
