//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18DemoEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int DetailsID { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public string PhoneNo { get; set; }
        public string FullAddress { get; set; }
    
        public virtual Emp Emp { get; set; }
    }
}
